name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
  NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'parking-helper-web/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./parking-helper-web
      run: npm ci
    
    - name: Run linter
      working-directory: ./parking-helper-web
      run: npm run lint
    
    - name: Run unit tests
      working-directory: ./parking-helper-web
      run: npm test -- --run
    
    - name: Build application
      working-directory: ./parking-helper-web
      run: npm run build
  
  e2e:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'parking-helper-web/package-lock.json'
    
    - name: Install dependencies
      working-directory: ./parking-helper-web
      run: npm ci
    
    - name: Install Playwright Browsers
      working-directory: ./parking-helper-web
      run: npx playwright install --with-deps
    
    - name: Run E2E tests
      working-directory: ./parking-helper-web
      run: npm run test:e2e
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: parking-helper-web/playwright-report/
        retention-days: 30